#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from moveit_msgs.srv import GetPositionIK
from moveit_msgs.msg import PositionIKRequest
from geometry_msgs.msg import PoseStamped
from scipy.spatial.transform import Rotation as R
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt

class ReachabilityVerifier(Node):
    def __init__(self):
        super().__init__("reachability_verifier")
        
        # Create IK Client
        self.ik_client = self.create_client(GetPositionIK, "/compute_ik")
        self.group_name = "arm" 
        self.base_frame = "link1" # Double check this is your 5-DOF root link!
        self.end_link = "end_effector_link"

    def wait_for_service(self):
        self.get_logger().info("Waiting for MoveIt /compute_ik service...")
        return self.ik_client.wait_for_service(timeout_sec=5.0)

    def verify_poses(self, csv_5dof, csv_6dof):
        if not self.wait_for_service():
            self.get_logger().error("Service not available! Is your 5-DOF MoveIt running?")
            return None

        print("\n" + "="*80)
        print(" 🔍 STARTING IK VERIFICATION & EXCLUSIVE WORKSPACE ANALYSIS")
        print("="*80)

        # 1. Load Data & Add Source Tracking (As suggested by the feedback!)
        df5 = pd.read_csv(csv_5dof)
        df5['source'] = '5dof'
        
        df6 = pd.read_csv(csv_6dof)
        df6['source'] = '6dof'
        
        # Combine
        df = pd.concat([df5, df6], ignore_index=True)
        df['reachable_by_5dof'] = False # Default to False
        
        total_poses = len(df)
        
        # Prepare IK Request
        req = GetPositionIK.Request()
        ik_req = PositionIKRequest()
        ik_req.group_name = self.group_name
        ik_req.ik_link_name = self.end_link
        ik_req.avoid_collisions = False 
        ik_req.timeout.sec = 0
        ik_req.timeout.nanosec = 50000000 # 50ms timeout

        start_time = time.time()

        # 2. Query MoveIt IK
        for index, row in df.iterrows():
            if index % 1000 == 0 and index > 0:
                rate = index / (time.time() - start_time)
                print(f"⏳ Checked {index}/{total_poses} poses... ({rate:.1f} poses/sec)")

            # RPY to Quaternion
            rot = R.from_euler('xyz', [row['roll'], row['pitch'], row['yaw']], degrees=False)
            qx, qy, qz, qw = rot.as_quat()

            # Construct Pose
            pose = PoseStamped()
            pose.header.frame_id = self.base_frame
            pose.pose.position.x = row['x']
            pose.pose.position.y = row['y']
            pose.pose.position.z = row['z']
            pose.pose.orientation.x = qx
            pose.pose.orientation.y = qy
            pose.pose.orientation.z = qz
            pose.pose.orientation.w = qw

            ik_req.pose_stamped = pose
            req.ik_request = ik_req

            # Call Service
            future = self.ik_client.call_async(req)
            rclpy.spin_until_future_complete(self, future)
            resp = future.result()
            
            # Error Code 1 == SUCCESS
            if resp and resp.error_code.val == 1:
                df.at[index, 'reachable_by_5dof'] = True

        total_time = time.time() - start_time
        
        # 3. Print Statistical Breakdown
        print("\n" + "="*80)
        print(" 📊 VERIFICATION RESULTS")
        print("="*80)
        
        # Stats for 5DOF generated poses
        df5_subset = df[df['source'] == '5dof']
        success_5dof = df5_subset['reachable_by_5dof'].sum()
        print(f"Poses originally generated by 5-DOF: {len(df5_subset)}")
        print(f" -> Reachable by 5-DOF: {success_5dof} ({(success_5dof/len(df5_subset))*100:.1f}%)")
        
        # Stats for 6DOF generated poses
        df6_subset = df[df['source'] == '6dof']
        success_6dof = df6_subset['reachable_by_5dof'].sum()
        print(f"\nPoses originally generated by 6-DOF: {len(df6_subset)}")
        print(f" -> Reachable by 5-DOF: {success_6dof} ({(success_6dof/len(df6_subset))*100:.1f}%)")
        print(f" -> UNREACHABLE (Exclusive to 6-DOF): {len(df6_subset) - success_6dof}")
        print("="*80)
        
        # Save dataset
        out_filename = "verified_kinematic_overlap.csv"
        df.to_csv(out_filename, index=False)
        print(f"💾 Saved full dataset with reachability flags to: {out_filename}")
        
        return df

def plot_exclusive_workspace(df):
    print("\n🎨 Generating Exclusive Workspace Plot for Research Paper...")
    
    # Split data
    shared_workspace = df[df['reachable_by_5dof'] == True]
    exclusive_6dof = df[(df['source'] == '6dof') & (df['reachable_by_5dof'] == False)]
    
    # Subsample for a cleaner plot (optional, but good for 16k points)
    sample_shared = shared_workspace.sample(n=min(2000, len(shared_workspace)), random_state=42)
    sample_exclusive = exclusive_6dof.sample(n=min(2000, len(exclusive_6dof)), random_state=42)
    
    fig = plt.figure(figsize=(10, 8), dpi=300)
    ax = fig.add_subplot(111, projection='3d')
    
    # Plot Shared Workspace (Blue)
    ax.scatter(sample_shared['x'], sample_shared['y'], sample_shared['z'], 
               c='#1f77b4', s=5, alpha=0.3, label='Shared Workspace (Both Robots)')
               
    # Plot Exclusive 6-DOF Workspace (Red)
    ax.scatter(sample_exclusive['x'], sample_exclusive['y'], sample_exclusive['z'], 
               c='#d62728', s=10, alpha=0.8, label='Exclusive Workspace (6-DOF ONLY)')
    
    ax.set_title("Kinematic Overlap: Shared vs Exclusive Workspace", fontsize=16, fontweight='bold')
    ax.set_xlabel('X [m]')
    ax.set_ylabel('Y [m]')
    ax.set_zlabel('Height (Z) [m]')
    
    # Keep aspect ratio square
    max_range = 0.5
    ax.set_xlim([-max_range, max_range])
    ax.set_ylim([-max_range, max_range])
    ax.set_zlim([-0.25, 0.5])
    
    # Add Legend
    ax.legend(markerscale=3, loc='upper right')
    
    plot_filename = "Fig5_Exclusive_Workspace.png"
    plt.savefig(plot_filename, bbox_inches='tight')
    print(f"✅ Saved high-resolution plot to: {plot_filename}")

def main(args=None):
    rclpy.init(args=args)
    
    # === UPDATE THESE FILENAMES TO MATCH YOUR SAVED CSVs ===
    csv_5dof = "omx_all_reachable_poses_5dof.csv"
    csv_6dof = "omx_all_reachable_poses_6dof.csv"
    
    verifier = ReachabilityVerifier()
    df_result = verifier.verify_poses(csv_5dof, csv_6dof)
    
    if df_result is not None:
        plot_exclusive_workspace(df_result)
        
    verifier.destroy_node()
    rclpy.shutdown()

if __name__ == "__main__":
    main()