import os
import glob
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings

import rclpy
from moveit_msgs.srv import GetPositionIK
from geometry_msgs.msg import PoseStamped, Pose

# Ignore warnings from np.nanmean if an array is completely empty
warnings.filterwarnings("ignore", category=RuntimeWarning)

class IKPerformanceAnalyzer:

    def __init__(self, node, group_name="manipulator", base_link="base_link"):
        self.node = node
        self.group_name = group_name
        self.base_link = base_link

        # ------------------------------------------------
        # ROS 2 SERVICE SETUP
        # ------------------------------------------------
        self.node.get_logger().info("⏳ Waiting for MoveIt IK service '/compute_ik'...")
        self.ik_client = self.node.create_client(GetPositionIK, "/compute_ik")
        
        if not self.ik_client.wait_for_service(timeout_sec=10.0):
            self.node.get_logger().error("❌ IK service '/compute_ik' not available!")
            raise RuntimeError("IK service not found.")
        self.node.get_logger().info("✅ MoveIt IK service connected.")

        # ------------------------------------------------
        # DIRECTORY SETUP
        # ------------------------------------------------
        self.output_dir = "ik_metrics"
        self.plots_dir = os.path.join(self.output_dir, "plots")
        self.dist_dir = os.path.join(self.output_dir, "distributions")

        # Create directories if they don't exist
        os.makedirs(self.output_dir, exist_ok=True)
        os.makedirs(self.plots_dir, exist_ok=True)
        os.makedirs(self.dist_dir, exist_ok=True)

        self.node.get_logger().info("📂 IKPerformanceAnalyzer initialized successfully.")
        self.node.get_logger().info(f"📁 Output directories ready: {self.output_dir}, {self.plots_dir}, {self.dist_dir}")

    # ------------------------------------------------
    # DATASET LOADING
    # ------------------------------------------------
    def load_latest_dataset(self):
        self.node.get_logger().info("🔍 Searching for the latest Forward Kinematics (FK) dataset...")

        # Look for the dataset generated by Module 2
        csv_files = glob.glob("workspace_fk_dataset_*.csv")

        if not csv_files:
            self.node.get_logger().error("❌ No FK dataset found. Please run Module 2 first!")
            return None

        # Get the most recently created file
        latest = max(csv_files, key=os.path.getctime)
        self.node.get_logger().info(f"✅ Found latest dataset: {latest}")

        return latest

    # ------------------------------------------------
    # IK SERVICE WRAPPER
    # ------------------------------------------------
    def _call_ik_service(self, p, q):
        """Builds the request, calls the /compute_ik service, and formats the result."""
        req = GetPositionIK.Request()
        req.ik_request.group_name = self.group_name
        req.ik_request.timeout.sec = 1
        
        pose = Pose()
        pose.position.x = float(p[0])
        pose.position.y = float(p[1])
        pose.position.z = float(p[2])
        
        if q is not None:
            pose.orientation.x = float(q[0])
            pose.orientation.y = float(q[1])
            pose.orientation.z = float(q[2])
            pose.orientation.w = float(q[3])
        else:
            pose.orientation.w = 1.0

        req.ik_request.pose_stamped.header.frame_id = self.base_link
        req.ik_request.pose_stamped.pose = pose

        # Synchronous-like call inside the script
        future = self.ik_client.call_async(req)
        rclpy.spin_until_future_complete(self.node, future, timeout_sec=1.5)

        if not future.done():
            # Timeout
            return {"solutions":[], "iterations": 0, "residual": np.nan, "singular": 1}

        res = future.result()
        
        # MoveItErrorCodes.val == 1 means SUCCESS
        if res.error_code.val == 1:
            joint_positions = list(res.solution.joint_state.position)
            
            # NOTE: MoveIt /compute_ik only returns ONE solution. 
            # It also doesn't provide internal residual or iteration counts over ROS msgs.
            # We pass defaults here so your plots generate successfully.
            return {
                "solutions": [joint_positions],
                "iterations": 1, 
                "residual": 1e-6, 
                "singular": 0
            }
        else:
            return {
                "solutions":[],
                "iterations": 0,
                "residual": np.nan,
                "singular": 1 if res.error_code.val in[-31, -21] else 0  # Guessed singularity error bounds
            }

    # ------------------------------------------------
    # MAIN ANALYSIS PIPELINE
    # ------------------------------------------------
    def analyze(self):
        try:
            # 1. Load the data
            dataset = self.load_latest_dataset()
            if dataset is None:
                return None

            self.node.get_logger().info("⏳ Loading CSV into memory...")
            df = pd.read_csv(dataset)
            df = df.dropna(subset=["x", "y", "z"])

            # Extract positions
            poses = df[["x", "y", "z"]].values

            # Extract orientations (quaternions) if they exist
            if {"qx","qy","qz","qw"}.issubset(df.columns):
                self.node.get_logger().info("✅ Orientation data (quaternions) found. IK will solve for full 6D poses.")
                quats = df[["qx","qy","qz","qw"]].values
            else:
                self.node.get_logger().warning("⚠️ No orientation data found. IK will solve for 3D position only.")
                quats = None

            total_poses = len(poses)
            self.node.get_logger().info(f"📊 Extracted {total_poses} valid poses for IK testing.")

            # Data storage lists
            success = []
            solve_times =[]
            solution_counts =[]
            residuals = []
            singular_flags = []
            iteration_counts =[]
            solution_diversity =[]

            self.node.get_logger().info("🚀 ========================================================")
            self.node.get_logger().info("🚀 STARTING INVERSE KINEMATICS (IK) PERFORMANCE BENCHMARK")
            self.node.get_logger().info("🚀 ========================================================")

            # 2. Iterate through every pose and test IK
            for i in range(total_poses):
                p = poses[i]
                q = None if quats is None else quats[i]

                # Start timer
                start = time.time()

                # CALL TO THE MOVEIT 2 SERVICE WRAPPER
                result = self._call_ik_service(p, q)

                # Stop timer
                solve_time = time.time() - start
                solve_times.append(solve_time)

                # Handle failure
                if result is None or len(result.get("solutions",[])) == 0:
                    success.append(0)
                    solution_counts.append(0)
                    residuals.append(np.nan) # NaN for failed residual
                    singular_flags.append(1 if result and result.get("singular") else 0)
                    iteration_counts.append(result.get("iterations", 0) if result else 0)
                    solution_diversity.append(0.0)
                
                # Handle Success
                else:
                    success.append(1)
                    sols = result.get("solutions",[])
                    
                    solution_counts.append(len(sols))
                    iteration_counts.append(result.get("iterations", 1))
                    residuals.append(result.get("residual", 0.0))
                    singular_flags.append(result.get("singular", 0))

                    # Calculate diversity (variance/spread of multiple solutions)
                    if len(sols) > 1:
                        solution_diversity.append(float(np.std(sols)))
                    else:
                        solution_diversity.append(0.0)

                # Progress printing every 5%
                print_interval = max(1, total_poses // 20)
                if (i + 1) % print_interval == 0 or (i + 1) == total_poses:
                    percent = ((i + 1) / total_poses) * 100
                    self.node.get_logger().info(f"⏳ Progress: {i + 1}/{total_poses} poses processed ({percent:.1f}%)")

            # 3. Convert lists to numpy arrays for fast math
            self.node.get_logger().info("🧮 Calculating aggregate metrics...")
            success = np.array(success)
            solve_times = np.array(solve_times)
            solution_counts = np.array(solution_counts)
            residuals = np.array(residuals)
            iteration_counts = np.array(iteration_counts)
            singular_flags = np.array(singular_flags)
            diversity = np.array(solution_diversity)

            # 4. Generate Dictionary of Metrics
            metrics = {
                "ik_success_rate": float(np.mean(success)),
                "ik_failure_rate": float(1.0 - np.mean(success)),
                "ik_mean_time": float(np.mean(solve_times)),
                "ik_solution_count_mean": float(np.mean(solution_counts)),
                "ik_singularity_rate": float(np.mean(singular_flags)),
                "ik_residual_mean": float(np.nanmean(residuals)) if not np.all(np.isnan(residuals)) else 0.0,
                "ik_iterations_mean": float(np.mean(iteration_counts))
            }

            self.node.get_logger().info(f"✅ IK Success Rate: {metrics['ik_success_rate']*100:.2f}%")
            self.node.get_logger().info(f"⏱️ Average Solve Time: {metrics['ik_mean_time']:.5f} seconds")

            # 5. Save Data to CSV
            metrics_file = os.path.join(self.output_dir, "ik_metrics_summary.csv")
            pd.DataFrame([metrics]).to_csv(metrics_file, index=False)
            self.node.get_logger().info(f"💾 Summary metrics saved to: {metrics_file}")

            dist_file = os.path.join(self.dist_dir, "ik_distributions.csv")
            pd.DataFrame({
                "success": success,
                "solve_time": solve_times,
                "solution_count": solution_counts,
                "iterations": iteration_counts,
                "residual": residuals,
                "diversity": diversity
            }).to_csv(dist_file, index=False)
            self.node.get_logger().info(f"💾 Distribution metrics saved to: {dist_file}")

            # 6. Generate Plots
            self.node.get_logger().info("📈 Generating visualization plots...")
            self.plot_success_bar(metrics)
            self.plot_time_histogram(solve_times)
            self.plot_time_boxplot(solve_times)
            self.plot_solution_hist(solution_counts)
            self.plot_solution_diversity(diversity)
            self.plot_iterations_hist(iteration_counts)
            self.plot_residual_distribution(residuals)
            self.plot_failure_bar(metrics)
            self.plot_singularity_bar(metrics)
            self.plot_ik_success_map(poses, success)

            self.node.get_logger().info("🎉 IK Performance Analysis Completed Successfully.")
            return metrics

        except Exception as e:
            self.node.get_logger().error(f"❌ IK analysis encountered a critical failure: {str(e)}")
            return None

    # ------------------------------------------------
    # PLOTTING FUNCTIONS
    # ------------------------------------------------

    def plot_success_bar(self, metrics):
        plt.figure(figsize=(6, 5))
        vals = [metrics["ik_success_rate"] * 100, metrics["ik_failure_rate"] * 100]
        plt.bar(["Success", "Failure"], vals, color=['#4CAF50', '#F44336'])
        plt.title("IK Success vs Failure Rate")
        plt.ylabel("Percentage (%)")
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.savefig(f"{self.plots_dir}/ik_success_rate.png")
        plt.close()

    def plot_time_histogram(self, times):
        plt.figure(figsize=(8, 5))
        plt.hist(times, bins=40, color='skyblue', edgecolor='black')
        plt.title("IK Computation Time Distribution")
        plt.xlabel("Solve Time (Seconds)")
        plt.ylabel("Frequency")
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.savefig(f"{self.plots_dir}/ik_time_histogram.png")
        plt.close()

    def plot_time_boxplot(self, times):
        plt.figure(figsize=(6, 5))
        plt.boxplot(times, patch_artist=True, boxprops=dict(facecolor="lightblue"))
        plt.title("IK Computation Time Box Plot")
        plt.ylabel("Solve Time (Seconds)")
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.savefig(f"{self.plots_dir}/ik_time_boxplot.png")
        plt.close()

    def plot_solution_hist(self, counts):
        plt.figure(figsize=(8, 5))
        plt.hist(counts, bins=range(0, int(max(counts)) + 2), color='purple', edgecolor='black', align='left')
        plt.title("IK Solution Count Distribution")
        plt.xlabel("Number of Solutions Found per Pose")
        plt.ylabel("Frequency")
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.savefig(f"{self.plots_dir}/ik_solution_count_hist.png")
        plt.close()

    def plot_solution_diversity(self, diversity):
        plt.figure(figsize=(8, 5))
        clean_diversity = diversity[diversity > 0] # Only plot points that actually have diversity > 0
        if len(clean_diversity) > 0:
            plt.scatter(range(len(clean_diversity)), clean_diversity, s=5, color='orange', alpha=0.6)
        plt.title("IK Solution Diversity (Std Dev among multiple solutions)")
        plt.xlabel("Pose Index (Filtered)")
        plt.ylabel("Joint Space Variance")
        plt.grid(True, linestyle='--', alpha=0.5)
        plt.savefig(f"{self.plots_dir}/ik_solution_diversity.png")
        plt.close()

    def plot_iterations_hist(self, iterations):
        plt.figure(figsize=(8, 5))
        plt.hist(iterations, bins=30, color='teal', edgecolor='black')
        plt.title("IK Convergence Iterations Distribution")
        plt.xlabel("Number of Iterations")
        plt.ylabel("Frequency")
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.savefig(f"{self.plots_dir}/ik_iterations_hist.png")
        plt.close()

    def plot_residual_distribution(self, residuals):
        plt.figure(figsize=(8, 5))
        clean = residuals[~np.isnan(residuals)]
        if len(clean) > 0:
            plt.hist(clean, bins=40, color='salmon', edgecolor='black')
        plt.title("IK Residual Error Distribution")
        plt.xlabel("Residual Error (Distance/Rotation Delta)")
        plt.ylabel("Frequency")
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.savefig(f"{self.plots_dir}/ik_residual_distribution.png")
        plt.close()

    def plot_failure_bar(self, metrics):
        plt.figure(figsize=(5, 5))
        plt.bar(["Failure Rate"], [metrics["ik_failure_rate"] * 100], color='#F44336')
        plt.title("IK Failure Rate")
        plt.ylabel("Percentage (%)")
        plt.ylim(0, max(10, metrics["ik_failure_rate"] * 100 + 5)) # Scale nicely
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.savefig(f"{self.plots_dir}/ik_failure_rate.png")
        plt.close()

    def plot_singularity_bar(self, metrics):
        plt.figure(figsize=(5, 5))
        plt.bar(["Singularity Rate"], [metrics["ik_singularity_rate"] * 100], color='#FF9800')
        plt.title("IK Singularity Rate")
        plt.ylabel("Percentage (%)")
        plt.ylim(0, max(10, metrics["ik_singularity_rate"] * 100 + 5))
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.savefig(f"{self.plots_dir}/ik_singularity_rate.png")
        plt.close()
    
    def plot_ik_success_map(self, poses, success):
        """Generates a 3D scatter plot of the workspace showing IK successes and failures."""
        fig = plt.figure(figsize=(10, 8))
        ax = fig.add_subplot(111, projection='3d')
        
        # Filter points by success flag
        success_pts = poses[success == 1]
        fail_pts = poses[success == 0]
        
        # Plot Successes (Green, smaller, slightly transparent so we can see inside)
        if len(success_pts) > 0:
            ax.scatter(success_pts[:, 0], success_pts[:, 1], success_pts[:, 2], 
                       c='#2ecc71', s=2, alpha=0.2, label='IK Success')
            
        # Plot Failures (Red, slightly larger, plotted second so they stand out)
        if len(fail_pts) > 0:
            ax.scatter(fail_pts[:, 0], fail_pts[:, 1], fail_pts[:, 2], 
                       c='#e74c3c', s=8, alpha=0.8, label='IK Failure')
        
        ax.set_title("3D Workspace IK Success Map", fontweight='bold')
        ax.set_xlabel("X (meters)")
        ax.set_ylabel("Y (meters)")
        ax.set_zlabel("Z (meters)")
        
        # # Customize legend
        # leg = ax.legend()
        # for handle in leg.legend_handles:
        #     handle.set_alpha(1.0) # Make legend markers fully opaque
        #     handle._sizes = [40]  # Make legend markers visible

        # Customize legend safely for all matplotlib versions
        leg = ax.legend()
        handles = getattr(leg, "legend_handles", getattr(leg, "legendHandles",[]))
        for handle in handles:
            handle.set_alpha(1.0) # Make legend markers fully opaque
            handle._sizes = [40]  # Make legend markers visible
            
        plt.savefig(f"{self.plots_dir}/ik_workspace_success_map.png", bbox_inches='tight')
        plt.close()